### ISSUE TITLE
Create automatic pressing nitro

### ISSUE THREAD

**Issue by User123456789012345678901234567890** [kgsensei/NitroTypeHack2#12]
Hello kgsensei,
If it is possible, could you please implement a feature where your application would have a option where you can automatically use nitro boost? Let the bot use the nitro boost on the longest word. If it is out of your capabilities, then just let the bot use the nitro randomly.

**Comment by kgsensei** [comment]
Please see -> https://github.com/kgsensei/NitroTypeHack2/releases/tag/3.2

**Comment by User123456789012345678901234567890** [comment]
Thank you very much!

BTW im JaYdEn in your discord.
