### ISSUE TITLE
Automation of Solving CAPTCHA

### ISSUE THREAD

**Issue by User123456789012345678901234567890** [kgsensei/NitroTypeHack2#15]
Hi, 
It's me again. I know you are really busy right now, but I just wanted to make sure that after you are done with your project you would not forget this important feature. The background running option is also very important, so I suggest the next time you release a update maybe make it V4.0.

**Comment by LightningPandaSO** [comment]
Yeha

**Comment by kgsensei** [comment]
This is way above my paygrade. Sorry, a CAPTCHA solver isn't going to be coming soon. Your best bet is just doing the CAPTCHA by hand. If you want, I can add a feature that will send you a notification when a CAPTCHA needs to be solved.
