### ISSUE TITLE
it has already banned me on 5 accounts

### ISSUE THREAD

**Issue by backupmanager-115** [kgsensei/NitroTypeHack2#16]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]
 - Browser [e.g. Chrome, Safari]
 - Version [e.g. 1.0, 1.1]

**Additional context**

**Comment by kgsensei** [comment]
Irresponsible use of this cheat can get you banned. If you go too fast or have too high of an accuracy you can be banned. If you don't change the speed and accuracy occasionally you can get banned. Using a modified game client to increase your odds against other players always has the chance of getting an account banned. As stated in the cheat and on download pages, I am not responsible for consequences of using this cheat.

On the bright side NitroType doesn't require an email for their account system so you can just keep creating new accounts when your old accounts get banned.
