### ISSUE TITLE
Won't allow me to open application.

### ISSUE THREAD

**Issue by AzureFume** [kgsensei/NitroTypeHack2#5]
It won't let me open the application, I click it, it loads, but doesn't open the application.

**Comment by kgsensei** [comment]
Can you provide me with a screenshot of the application?

**Comment by AzureFume** [comment]
I can't open it,
I click it and nothing happens.

**Comment by kgsensei** [comment]
Are you on a windows computer?

**Comment by AzureFume** [comment]
Yes I am.

**Comment by kgsensei** [comment]
What is the size of your screen?
