### ISSUE TITLE
about the hack an you should creat

### ISSUE THREAD

**Issue by shiestyla** [kgsensei/NitroTypeHack2#6]
hey so i see tht you can install it  an  since sum people who have school chromebooks an laptops  want to download it  cant because they school have it blocked where they cant install it or run it i was thinking if you can make a bookmark javascript or hack were we  still can do the same thing is just we can run it through bookmark bar  like click on it an it pop up the hack  i think alot of people would love it if you can do it like tht too so we can still use it an we just can put the javascript inside the book mark were we book mark a tab an we got to url an past the javascript in there an save it an then go to nitro type an click on it an it pop up the hack an we can run it. if you can do that it will be awesome

**Comment by OPstriker** [comment]
Currently (ATM) the Hack only works on windows, Javascript Implementation could be possible (I maybe wrong), but thats up to the Dev.
